$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
type: pipeline
name: nemo_multitask_prompt_and_ptuning_pipeline
version: 9
display_name: nemo pipeline component with multitask prompt and ptuning
description: etects one or more faces in a given image or video. Some of the major steps covered in the pipeline are, but not limited to Take a pretrained resnet18 model and train a ResNet-18 FaceNet model on the WIDERFACE dataset, Prune the trained FaceNet model, Retrain the pruned model to recover lost accuracy, Export the pruned model, Run Inference on the trained model <a href=https://github.com/NVIDIA/NVIDIA_AI_Enterprise_AzureML/blob/main/src/pipelines/tao/object_detection/facenet/tao_facenet_pipeline/README.md>Reference file</a>
tags:
    NVIDIA AI Enterprise: ""
    Preview: ""
inputs:
  urls:
    type: string
  file_types:
    type: string 
  checksums:
    type: string
    default: 'NA'
  local_subdirs:
    type: string
  script_subdir:
    type: string
  script_filename:
    type: string
  parameters:
    type: string
  data_subdir:
    type: string
  place_holder:
    type: string
  source_config_subdir:
    type: string
  source_config_filename:
    type: string
  train_filename:
    type: string
  val_filename:
    type: string
  model_subdir:
    type: string
  model_filename:
    type: string
  compute_train_node:
    type: string
outputs:
  data_dir:
    type: uri_folder
  processed_data_dir:
    type: uri_folder
  new_config_dir:
    type: uri_folder
jobs: 
  download_data:
    type: command
    component: azureml://registries/NVIDIA-NGC-Test/components/download_multiple_streams/versions/7
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      urls: ${{parent.inputs.urls}}
      file_types: ${{parent.inputs.file_types}}
      checksums: ${{parent.inputs.checksums}}
      local_subdirs: ${{parent.inputs.local_subdirs}}
    outputs:
      data_dir: ${{parent.outputs.data_dir}}
  process_data:
    type: command
    component: azureml://registries/NVIDIA-NGC-Test/components/nemo_process_data/versions/4
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      script_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      script_subdir: ${{parent.inputs.script_subdir}}
      script_filename: ${{parent.inputs.script_filename}}
      parameters: ${{parent.inputs.parameters}}
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      data_subdir: ${{parent.inputs.data_subdir}}
      place_holder: ${{parent.inputs.place_holder}}
    outputs:
      processed_data_dir: ${{parent.outputs.processed_data_dir}}    
  p_tuning_model_config_setup:
    type: command
    component: azureml://registries/NVIDIA-NGC-Test/components/p_tuning_model_config_setup/versions/1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      source_config_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      source_config_subdir: ${{parent.inputs.config_subdir}
      source_config_filename: ${{parent.inputs.config_filename}}
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      data_subdir: ${{parent.inputs.data_subdir}}
      train_filename: ${{parent.inputs.train_filename}}
      val_filename: ${{parent.inputs.val_filename}}
      model_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      model_subdir: ${{parent.inputs.model_subdir}}
      model_filename: ${{parent.inputs.model_filename}}
outputs:
  new_config_dir: ${{parent.outputs.processed_data_dir}} 