$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: p_tuning_model_config_setup
display_name: p_tuning_model_config_setup
description: It allows the specification of the number of epochs to be used <a href=https://github.com/NVIDIA/NVIDIA_AI_Enterprise_AzureML/tree/main/src/components/tao/object_detection/detectnet_v2/tao_detectnet_v2_train/README.md>Reference file</a> 
version: 1
type: command
tags:
    NVIDIA AI Enterprise: ""
    Preview: ""
inputs:
  source_config_dir:
    type: uri_folder
  source_config_subdir:
    type: string
  source_config_filename:
    type: string
  data_dir:
    type: uri_folder
  data_subdir:
    type: string
  train_filename:
    type: string
  val_filename:
    type: string
  model_dir:
    type: uri_folder
  model_subdir:
    type: string
  model_filename:
    type: string
outputs:
  new_config_dir:
    type: uri_folder
code: ./src
environment:  azureml://registries/<registry_name>/environments/nvidia_nemo_23_03/versions/1
command: >-
  python3 ./p_tuning_model_config_setup
      --source_config_file $source_config_dir/$source_config_subdir/$source_config_filename
      --model-file $model_dir/$model_subdir/$model_filename
      --train-file $data_dir/$data_subdir/$train_filename
      --val-file $data_dir/$data_subdir/$val_filename
      --dest_config_file $new_config_dir/$source_config_filename