FROM nvcr.io/nvidian/nemo-llm/nemollm-inference-trt-only:24.02.rc2
ENTRYPOINT []
EXPOSE 8000
ADD scripts/auxiliary_files/deploy_models.sh ./deploy_models.sh
CMD ./deploy_models.sh ${AZUREML_MODEL_DIR}