$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: nyc_taxi_data_regression_with_NVIDIA_RAPIDS
description: Train regression model based on nyc taxi dataset using Nvidia RAPIDS
tags:
  Preview: ''
# <inputs_and_outputs>

outputs: 
  pipeline_job_trained_model:
    type: mlflow_model
    mode: rw_mount
  pipeline_job_predictions:
    mode: rw_mount 
  pipeline_job_score_report:
    mode: rw_mount
# </inputs_and_outputs>

# <jobs>
settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:mayani-gpuT4-cluster
  continue_on_step_failure: false

jobs:
  prep_job:
    type: command
    component: azureml://registries/NVIDIARegistryTest1/components/prep_taxi_data/versions/1
    inputs:
      raw_data: #using local data, will crate an anonymous data asset
        type: uri_folder
        path: azureml://subscriptions/b7d41fc8-d35d-41db-92ed-1f7f1d32d4d9/resourcegroups/mayani-rg/workspaces/mayani-ws2-europe/datastores/workspaceblobstore/paths/UI/2023-05-09_170750_UTC/data/
    outputs:
      prep_data: 

  transform_job:
    type: command
    component: azureml://registries/NVIDIARegistryTest1/components/taxi_feature_engineering/versions/1
    inputs:
      clean_data: ${{parent.jobs.prep_job.outputs.prep_data}}
    outputs:
      transformed_data: 

  train_job:
    type: command
    component: azureml://registries/NVIDIARegistryTest1/components/train_linear_regression_model/versions/1
    inputs:
      training_data: ${{parent.jobs.transform_job.outputs.transformed_data}}
    outputs:
      model_output: ${{parent.outputs.pipeline_job_trained_model}}
      test_data: 
  
  predict_job:
    type: command
    component: azureml://registries/NVIDIARegistryTest1/components/predict_taxi_fares/versions/1
    inputs:
      model_input: ${{parent.jobs.train_job.outputs.model_output}}
      test_data: ${{parent.jobs.train_job.outputs.test_data}}
    outputs:
      predictions: ${{parent.outputs.pipeline_job_predictions}}

  score_job:
    type: command
    component: azureml://registries/NVIDIARegistryTest1/components/score_model/versions/1
    inputs:
      predictions: ${{parent.jobs.predict_job.outputs.predictions}}
      model: ${{parent.jobs.train_job.outputs.model_output}}
    outputs:
      score_report: ${{parent.outputs.pipeline_job_score_report}}
# </jobs>