# <component>
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: rapids_train_linear_regression_model
display_name: TrainLinearRegressionModel
version: 1
description: Component for training the model using Linear Regression <a href=https://github.com/NVIDIA/NVIDIA_AI_Enterprise_AzureML/tree/main/src/components/RAPIDS/NYC_taxi_with_regression/Train_component/README.md>READ ME</a>
tags:
  'NVIDIA AI Enterprise': '3.1'
  Preview: ''
type: command
inputs:
  training_data: 
    type: uri_folder
  test_split_ratio:
    type: number
    min: 0
    max: 1
    default: 0.2
outputs:
  model_output:
    type: mlflow_model
  test_data:
    type: uri_folder
code: ./train_src
environment: azureml://registries/<REGISTRY>/environments/NVIDIA-rapids/versions/1
command: >-
  python train.py 
  --training_data ${{inputs.training_data}} 
  --test_data ${{outputs.test_data}} 
  --model_output ${{outputs.model_output}}
  --test_split_ratio ${{inputs.test_split_ratio}}
# </component>
