name: monai_train_env
version: 1
build:
  path: ./src
description: Environment using nvcr.io/nvidia/clara/monai-toolkit:1.0. <a href=https://catalog.ngc.nvidia.com/orgs/nvidia/teams/clara/containers/monai-toolkit</a> 
