set -x

# map the output data location to the directory name used by the script

export ORIGINAL_SPECs_DIR=$1
export SPEC_FILE=$2
export TRAINING_DATA_DIR=$3
export SPECFILE_REFERENCE_TRAINING_DATA_DIR=$4
export VALIDATION_DATA_DIR=$5
export SPECFILE_REFERENCE_VALIDATION_DATA_DIR=$6
export TRAINING_TF_RECORDS_DIR=$7
export SPECFILE_REFERENCE_TRAINING_TF_RECORDS_DIR=$8
export VALIDATION_TF_RECORDS_DIR=${9}
export SPECFILE_REFERENCE_VALIDATION_TF_RECORDS_DIR=${10}
export BASE_MODEL_DIR=${11}
export SPECFILE_REFERENCE_MODEL_DIR=${12}
export OUTPUT_SUBFOLDER=${13}
export OUTPUT_FILENAME=${14}
export OUTPUT_DIR=${15}
export UPDATED_SPECs_DIR=${15}/specs
export MAX_BATCHES=${16}
export USE_VALIDATION_SET=${16}

#base_model_subdir migth be not defined so /ND pattern needs to be removed
BASE_MODEL_DIR=`echo ${BASE_MODEL_DIR} | sed -e 's%/ND%%g'`

mkdir $OUTPUT_DIR
mkdir $UPDATED_SPECs_DIR

if [[ "${SPECFILE_REFERENCE_VALIDATION_DATA_DIR}" != "ND" ]]
then
    bash ./update_specs.sh ${ORIGINAL_SPECs_DIR} ${UPDATED_SPECs_DIR} ${SPEC_FILE} ${SPECFILE_REFERENCE_TRAINING_DATA_DIR}:${TRAINING_DATA_DIR},${SPECFILE_REFERENCE_VALIDATION_DATA_DIR}:${VALIDATION_DATA_DIR},${SPECFILE_REFERENCE_TRAINING_TF_RECORDS_DIR}:${TRAINING_TF_RECORDS_DIR},${SPECFILE_REFERENCE_VALIDATION_TF_RECORDS_DIR}:${VALIDATION_TF_RECORDS_DIR},${SPECFILE_REFERENCE_MODEL_DIR}:${BASE_MODEL_DIR}
else
    bash ./update_specs.sh ${ORIGINAL_SPECs_DIR} ${UPDATED_SPECs_DIR} ${SPEC_FILE} ${SPECFILE_REFERENCE_TRAINING_DATA_DIR}:${TRAINING_DATA_DIR},${SPECFILE_REFERENCE_TRAINING_TF_RECORDS_DIR}:${TRAINING_TF_RECORDS_DIR},${SPECFILE_REFERENCE_MODEL_DIR}:${BASE_MODEL_DIR}
fi

bash ./tao_detectnet_v2_calibration_tensorfile.sh ${UPDATED_SPECs_DIR} ${SPEC_FILE} ${OUTPUT_SUBFOLDER} ${OUTPUT_FILENAME} ${OUTPUT_DIR} ${MAX_BATCHES} ${USE_VALIDATION_SET}

ls -l $OUTPUT_DIR/${OUTPUT_SUBFOLDER}

