FROM nvcr.io/ea-bignlp/beta-inf-prerelease/infer:23.08.v7
EXPOSE 8000
CMD python /opt/NeMo/scripts/deploy/deploy_triton.py --nemo_checkpoint /models/GPT-2B/GPT-2B-001_bf16_tp1.nemo --model_type="gptnext" --triton_model_name GPT-2B
