$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: nemo-gpt-8b-deployment-1
endpoint_name: nemo-gpt-8b-endpoint-aml-mayani-1
#model: azureml://registries/NVIDIARegistryTest1/models/llama-2-13b-chat/versions/1
model: azureml://registries/NVIDIARegistryTest1/models/NV-GPT-8b/versions/1
#model_mount_path: /triton-models
environment: 
  name: tme_genai_model_server_nemo8b
  #image: mayanicontainerrg.azurecr.io/model-server:latest
  image: 5d74aef9562a4ac1b4616422f000bf12.azurecr.io/model-server-nvgpt:latest
  inference_config:
      liveness_route:
          path: /v2/health/live
          port: 8000
      readiness_route:
          path: /v2/health/ready
          port: 8000
      scoring_route:
          path: /
          port: 8000
instance_type: Standard_NC24ads_A100_v4
request_settings:
  request_timeout_ms: 10000
  max_concurrent_requests_per_instance: 512
  max_queue_wait_ms: 3000
liveness_probe:
  initial_delay: 900
  timeout: 1
  period: 5
  success_threshold: 1
  failure_threshold: 100
readiness_probe:
  initial_delay: 900
  timeout: 1
  period: 5
  success_threshold: 1
  failure_threshold: 100
instance_count: 1
