$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: nemo-llama-deployment-aml-1
endpoint_name: nemo-llama-endpoint-aml-1
model: azureml://registries/NVIDIA-AI-Enterprise-Preview/models/llama/versions/2
model_mount_path: /triton-models
environment: azureml://registries/NVIDIA-AI-Enterprise-Preview/environments/tme_genai_model_server-env/versions/7
instance_type: Standard_NC24ads_A100_v4
request_settings:
  request_timeout_ms: 10000
  max_concurrent_requests_per_instance: 512
  max_queue_wait_ms: 3000
liveness_probe:
  initial_delay: 900
  timeout: 1
  period: 5
  success_threshold: 1
  failure_threshold: 100
readiness_probe:
  initial_delay: 900
  timeout: 1
  period: 5
  success_threshold: 1
  failure_threshold: 100
instance_count: 1
