FROM nvcr.io/nv-nvaie-tme/genai-model-server:latest
ENTRYPOINT []
EXPOSE 8000
RUN mkdir /opt_temp/aux
ADD scripts/auxiliary_files/deploy_models.sh /opt_temp/aux/deploy_models.sh
CMD /opt_temp/aux/deploy_models.sh ${AZUREML_MODEL_DIR}