channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=21.2.4
- pip:
  - mlflow<3,>=2.2
  - cffi==1.15.1
  - cloudpickle==2.0.0
  - google-api-core==2.11.0
  - jsonschema==4.17.3
  - matplotlib==3.7.1
  - monai==1.1.0
  - nibabel==5.0.1
  - numpy==1.24.2
  - packaging==22.0
  - pandas==1.5.2
  - protobuf==3.20.3
  - psutil==5.9.4
  - pytorch-ignite==0.4.10
  - pyyaml==6.0
  - requests==2.28.1
  - scipy==1.10.0
  - tensorboard==2.12.0
  - torch==1.11.0
  - torchvision==0.12.0
  - tqdm==4.64.0
name: mlflow-env
