FROM nvcr.io/nvidia/tao/tao-toolkit-tf:v3.22.05-tf1.15.4-py3
ENTRYPOINT []

# Install pip dependencies
RUN pip install 'matplotlib>=3.3,<3.4' \
                'psutil>=5.8,<5.9' \
                'tqdm>=4.59,<4.60' \
                'pandas>=1.1,<1.2' \
                'scipy>=1.5,<1.6' \
                'numpy>=1.10,<1.20' \
                'azureml-core==1.45.0' \
                'azureml-defaults==1.45.0' \
                'azureml-mlflow==1.45.0' \
                'azureml-telemetry==1.45.0' \
                'scikit-learn==0.24.1' \
                'unzip' \
                'ipykernel' \
                'ipython' \
                'mlflow' \ 
                'pillow' \
                'jupyterlab'

