$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: next item prediction 

settings:
  default_compute: azureml:<gpu-cluster>
outputs:
  final_pipeline_output:
    mode: rw_mount

jobs:
  data_gen: 
    type: command 
    component: azureml://registries/<registry_name>/components/next_item_data_gen/versions/1
    outputs: 
      data_gen_output: 
        mode: rw_mount 
  data_prep:
    type: command
    component: azureml://registries/<registry_name>/components/next_item_data_prep_test/versions/1
    inputs: 
      data_prep_input: ${{parent.jobs.data_gen.outputs.data_gen_output}}
    outputs:
      data_prep_output: 
        mode: rw_mount
  train: 
    type: command 
    component: azureml://registries/<registry_name>/components/next_item_train_ensemble/versions/1
    inputs: 
      train_input: ${{parent.jobs.data_prep.outputs.data_prep_output}}
    outputs: 
      train_output: ${{parent.outputs.final_pipeline_output}}
