subscription_id="c81d69b0-e717-4018-99c9-7d71389d2355"
resource_group="nv-tme-rg"
workspace="tme-demo-ml"
registry_name=""
acr = ""
component_file=""
container_registry="" 

#vmsize="???"
#registry_name="???" 
#container="???"
#compute_name="???"
#product_subfolder="???"
#pipeline_path="pipelines/${nvidia_product}/${container}/$product_subfolder"
