set -x

# map the output data location to the directory name used by the script

export ORIGINAL_SPECs_DIR=$1
export SPEC_FILE=$2
export TRAINING_DATA_DIR=$3
export SPECFILE_REFERENCE_TRAINING_DATA_DIR=$4
export VALIDATION_DATA_DIR=$5
export SPECFILE_REFERENCE_VALIDATION_DATA_DIR=$6
export TRAINING_TF_RECORDS_DIR=$7
export SPECFILE_REFERENCE_TRAINING_TF_RECORDS_DIR=$8
export VALIDATION_TF_RECORDS_DIR=${9}
export SPECFILE_REFERENCE_VALIDATION_TF_RECORDS_DIR=${10}
export KEY=${11}
export BASE_MODEL_DIR=${12}
export SPECFILE_REFERENCE_MODEL_DIR=${13}
export MODEL_NAME=${14}
export MODEL_SUBFOLDER=${15}
export TARGET_MODEL_DIR=${16}
export UPDATED_SPECs_DIR=./specs
export FRAMEWORK=${17}
export USE_TRAINING_SET=${18}
export GPU_INDEX=${19}

mkdir $TARGET_MODEL_DIR
mkdir $UPDATED_SPECs_DIR

#base_model_subdir migth be not defined so /ND pattern needs to be removed
BASE_MODEL_DIR=`echo ${BASE_MODEL_DIR} | sed -e 's%/ND%%g'`

ls -l $TRAINING_DATA_DIR
ls -l $VALIDATION_DATA_DIR
ls -l $TRAINING_TF_RECORDS_DIR
ls -l $VALIDATION_TF_RECORDS_DIR
ls -l $BASE_MODEL_DIR

if [[ "${SPECFILE_REFERENCE_VALIDATION_DATA_DIR}" != "ND" ]]
then
    bash ./update_specs.sh ${ORIGINAL_SPECs_DIR} ${UPDATED_SPECs_DIR} ${SPEC_FILE} ${SPECFILE_REFERENCE_TRAINING_DATA_DIR}:${TRAINING_DATA_DIR},${SPECFILE_REFERENCE_VALIDATION_DATA_DIR}:${VALIDATION_DATA_DIR},${SPECFILE_REFERENCE_TRAINING_TF_RECORDS_DIR}:${TRAINING_TF_RECORDS_DIR},${SPECFILE_REFERENCE_VALIDATION_TF_RECORDS_DIR}:${VALIDATION_TF_RECORDS_DIR},${SPECFILE_REFERENCE_MODEL_DIR}:${BASE_MODEL_DIR}

else
    bash ./update_specs.sh ${ORIGINAL_SPECs_DIR} ${UPDATED_SPECs_DIR} ${SPEC_FILE} ${SPECFILE_REFERENCE_TRAINING_DATA_DIR}:${TRAINING_DATA_DIR},${SPECFILE_REFERENCE_TRAINING_TF_RECORDS_DIR}:${TRAINING_TF_RECORDS_DIR},${SPECFILE_REFERENCE_MODEL_DIR}:${BASE_MODEL_DIR}
fi

bash ./tao_detectnet_v2_evaluate.sh ${UPDATED_SPECs_DIR} ${SPEC_FILE} ${TARGET_MODEL_DIR} ${MODEL_SUBFOLDER} ${KEY} ${MODEL_NAME} ${FRAMEWORK} ${USE_TRAINING_SET} ${GPU_INDEX}

